Fixed the back-end error when tried to getting the user information.
wso2-extensions/identity-outbound-auth-dropbox pull request #2
Opened 2018-04-10 05:25 UTC by kalaiyarasiganeshalingam

## Purpose
Fixed #1.

## Goals
 changed the all dropbox's requirements according to the API v2 . 

## Approach
N/A

## User stories
N/A

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
N/A

## Training
N/A

## Certification
N/A

## Marketing
N/A

## Automation tests
 - Unit tests 
  N/A

 - Integration tests
N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
N/A

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
N/A
 
## Learning
N/A

2018-04-10 09:40 UTC, Kanapriya requested changes

2018-04-10 09:40 UTC, Kanapriya commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +        if (url == null) {
Use StringUtils for the null check

2018-04-10 09:40 UTC, Kanapriya commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +            throws IOException {
Formatting issue

2018-04-10 09:40 UTC, Kanapriya commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +        while (inputLine != null) {
Use StringUtils for null check

2018-04-10 09:40 UTC, Kanapriya commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +            log.debug("response: " + builder.toString());
Please add meaningful message to the debug logs

2018-04-11 02:44 UTC, dimslee requested changes

2018-04-11 02:44 UTC, muthulee commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +        reader.close();
Please close the resource stream on finally block or use try resource

2018-05-09 09:32 UTC, sameeragunarathne commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +            log.debug(" Dropbox user information : " + builder.toString());
Unwanted space in the start if the debug log message

2018-05-09 09:34 UTC, hasuniea commented on component/src/main/java/org/wso2/carbon/identity/authenticator/dropbox/DropboxAuthenticator.java
> +        urlConnection.setRequestMethod("POST");
Can't we use constants?

2018-05-09 10:07 UTC, hasuniea approved these changes

2018-05-09 10:10 UTC, dimslee approved these changes

2018-05-23 06:21 UTC, Kanapriya approved these changes

2018-05-23 07:25 UTC, sameeragunarathne approved these changes

2018-05-23 07:27 UTC, Kanapriya approved these changes

2018-05-23 07:28 UTC, Biruntha approved these changes

2018-06-04 07:10 UTC, menakaj reviewed
Please use proper commit messages. Fix in the other places as well.

2018-09-25 04:38 UTC, thanujalk approved these changes

2018-09-25 04:38 UTC, merged